app:
  title: "DataGenius PRO – Senior DS Copilot"
  theme: "auto" # auto|light|dark
  max_file_size_mb: 200
  sample_rows_for_eda: 50000
ml:
  test_size: 0.2
  random_state: 42
  n_jobs: -1
report:
  author: "DataGenius Team"
  company: "Your Company"
  logo_path: "assets/images/logo.svg"
